name: Test
on: [push, pull_request]
env:
  GO_VERSION: "~1"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    #
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
        check-latest: true
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -v ./...
